#!/bin/bash
#
# run_pa4.sh
# Sprint 4 main script. Builds off sprint 3 outputs.
#

set -euo pipefail


DATA=data

LOG=logs/run_pa4.log
ERROR=logs/errors_pa4.log

mkdir -p out/evidence logs

# Clear/create log files before each run so logs don't accumulate across runs
: > "${LOG}"
: > "${ERROR}"
exec > >(tee -a "${LOG}") 2> >(tee -a "${ERROR}" >&2)

# Prompt for the path to the sprint 3 output CSVs.
# The MIMIC-IV dataset location varies per machine, so this allows the
# TA/grader to point the script at wherever their sprint 3 outputs live.
# Press Enter to accept the default (out/evidence).
echo "Enter path to sprint 3 output CSVs [default: out/evidence]:"
read INPUT_PATH
# If the user pressed Enter without typing a path, fall back to the default
if [ -z "$INPUT_PATH" ]; then
  INPUT_PATH=out/evidence
fi

# OUT is used as the base directory for both input CSVs and output TSVs
OUT="$INPUT_PATH"

# Check that the path actually exists
if [ ! -d "$OUT" ]; then
  echo "Error: path does not exist: $OUT"
  exit 1
fi

# Check that required data/ files are present.
# These are generated by sprint 2 and used by sprint 3 — if missing, earlier scripts need to be run first.
for f in data/bc_admissions_patients.csv data/bc_patients.csv; do
  if [ ! -f "${f}" ]; then
    echo "Error: required data file not found: ${f}"
    exit 1
  fi
done

# Check that all required sprint 3 output files are present.
# If any are missing, exit with a clear error instead of failing silently later.
for f in bc_first_diagnosis.csv pre_bc_symptom_timeline.csv admission_counts_pre_bc.txt; do
  if [ ! -f "${OUT}/${f}" ]; then
    echo "Error: required file not found: ${OUT}/${f}"
    exit 1
  fi
done

# Clean bc_first_diagnosis.csv -> bc_first_diagnosis.tsv
# source cols: subject_id,hadm_id,admittime,icd_code
# strip quotes, remove brackets, remove thousands separators,
# convert comma delimiter to tab, trim leading/trailing whitespace,

# then fill empty fields with NA.
# after converting commas to tabs, an empty field looks like \t\t (two tabs in a row).
# s/\t\t/\tNA\t/ replaces it with NA in the middle.
# s/^\t/NA\t/ handles an empty first field (line starts with a tab).
# s/\t$/\tNA/ handles an empty last field (line ends with a tab).
sed -E \
  -e 's/"([^"]*)"/\1/g' \
  -e 's/\[//g' \
  -e 's/\]//g' \
  -e 's/([0-9]),([0-9]{3})/\1\2/g' \
  -e 's/[[:space:]]*,[[:space:]]*/\t/g' \
  -e 's/^[[:space:]]+//; s/[[:space:]]+$//' \
  "${OUT}/bc_first_diagnosis.csv" \
| sed -E \
  -e 's/\t\t/\tNA\t/g' \
  -e 's/^\t/NA\t/' \
  -e 's/\t$/\tNA/' \
> "${OUT}/bc_first_diagnosis.tsv"

# Clean pre_bc_symptom_timeline.csv -> pre_bc_symptom_timeline.tsv
# source cols: subject_id,row_type,hadm_id,admittime,seq_num,icd_code
# strip quotes, remove brackets, remove thousands separators,
# convert comma delimiter to tab, trim leading/trailing whitespace,
# then fill empty fields with NA
sed -E \
  -e 's/"([^"]*)"/\1/g' \
  -e 's/\[//g' \
  -e 's/\]//g' \
  -e 's/([0-9]),([0-9]{3})/\1\2/g' \
  -e 's/[[:space:]]*,[[:space:]]*/\t/g' \
  -e 's/^[[:space:]]+//; s/[[:space:]]+$//' \
  "${OUT}/pre_bc_symptom_timeline.csv" \
| sed -E \
  -e 's/\t\t/\tNA\t/g' \
  -e 's/^\t/NA\t/' \
  -e 's/\t$/\tNA/' \
> "${OUT}/pre_bc_symptom_timeline.tsv"

# BEFORE/AFTER sample file
# Writes head -n 5 of each CSV (before) and TSV (after) into one file for review
{
  echo "BEFORE: bc_first_diagnosis.csv (head -n 5)"
  head -n 5 "${OUT}/bc_first_diagnosis.csv"
  echo ""
  echo "AFTER:  bc_first_diagnosis.tsv (head -n 5)"
  head -n 5 "${OUT}/bc_first_diagnosis.tsv"
  echo ""
  echo "BEFORE: pre_bc_symptom_timeline.csv (head -n 5)"
  head -n 5 "${OUT}/pre_bc_symptom_timeline.csv"
  echo ""
  echo "AFTER:  pre_bc_symptom_timeline.tsv (head -n 5)"
  head -n 5 "${OUT}/pre_bc_symptom_timeline.tsv"
} > out/cleaned_sample.tsv

echo "sample written to out/cleaned_sample.tsv"

# Sanity checks
echo "bc_first_diagnosis row count:"
wc -l "${OUT}/bc_first_diagnosis.csv" "${OUT}/bc_first_diagnosis.tsv"

echo "pre_bc_symptom_timeline row count:"
wc -l "${OUT}/pre_bc_symptom_timeline.csv" "${OUT}/pre_bc_symptom_timeline.tsv"


# =============================================================================
# BHOOMIKA'S SECTION
# =============================================================================

# =========================================================
# PART 2: AWK Quality Filtering
#
# Goal:
# Keep only valid rows from the dataset.
#
# Keep rows where:
#   - subject_id is non-empty and not 0
#   - hadm_id is non-empty
#   - admittime starts with a valid year (YYYY)
#   - icd_code is non-empty
#
# Drop malformed or null rows
#
# Important:
#   - Input is CSV → delimiter = ","
#   - Output is TSV → delimiter = "\t"
#   - NR==1 preserves header
# =========================================================

echo "=== PART 2: AWK Quality Filtering ==="

awk -F',' '
BEGIN { OFS="\t" }

# Preserve header (convert commas → tabs)
NR == 1 {
  print $1, $2, $3, $4, $5, $6
  next
}

# Filter conditions
($1 == "" || $1 == "0" || $1 == "NA") { next }
($3 == "" || $3 == "NA") { next }

# match() checks if admittime starts with YYYY
(match($4, /^[0-9]{4}/) == 0) { next }

($6 == "" || $6 == "NA") { next }

# Print valid rows (CSV → TSV conversion)
{ print $1, $2, $3, $4, $5, $6 }
' "${OUT}/pre_bc_symptom_timeline.csv" \
| sort -t$'\t' -k1,1n -k4,4 \
> "${OUT}/filtered_sample.tsv"

echo "Created: ${OUT}/filtered_sample.tsv"
wc -l "${OUT}/filtered_sample.tsv"
head -n 5 "${OUT}/filtered_sample.tsv"


# =========================================================
# PART 4A: Patient Visits (Temporal Structuring)
#
# Goal:
# Group rows by (subject_id + hadm_id)
# → each pair = one hospital visit
#
# Count distinct ICD codes per visit
#
# Important concepts:
#   - SUBSEP allows multi-key indexing in awk
#   - seen_code[] ensures unique counting
# =========================================================

echo "=== PART 4A: Patient Visits ==="


#Task 3
# Build out/buckets.tsv

awk '
BEGIN {
  OFS="\t"
}

# first file: count total visits per subject_id
NR==FNR {
  if (FNR==1) next
  n = split($0, a, ",")
  sid = a[1]
  total[sid]++
  ids[sid] = 1
  next
}

# skip header of second file
FNR==1 { next }

# second file: get pre_dx_visits per subject_id
{
  n = split($0, a, "\t")
  sid = a[1]
  cnt = a[2]

  # skip bad rows with missing values
  if (sid == "" || cnt == "") next

  pre[sid] = cnt
  ids[sid] = 1
}

END {
  # print header
  print "subject_id","total_visits","pre_dx_visits","pre_dx_ratio","bucket"

  for (sid in ids) {
    tv = (sid in total ? total[sid] : 0)
    pv = (sid in pre ? pre[sid] : 0)

    # avoid divide by 0
    if (tv == 0) {
      ratio = "NA"
    } else {
      ratio = sprintf("%.3f", pv / tv)
    }

    # assign bucket based on pre_dx_visits
    if (pv == 0) {
      bucket = "ZERO"
    } else if (pv == 1) {
      bucket = "LOW"
    } else if (pv == 2) {
      bucket = "MID"
    } else {
      bucket = "HIGH"
    }

    print sid, tv, pv, ratio, bucket
  }
}
' data/bc_admissions_patients.csv out/evidence/admission_counts_pre_bc.txt \
| sort -t$'\t' -k1,1n > out/buckets.tsv

echo "buckets written to out/buckets.tsv"
head -n 5 out/buckets.tsv




# Task 5: Build out/patient_summary.tsv

awk -F'\t' '
BEGIN { OFS="\t" }

# Skip header
NR == 1 { next }

{
  sid  = $1
  hadm = $3
  time = $4
  code = $6

  # Create a unique key for each visit
  visit_key = sid SUBSEP hadm

  # Store admission time for that visit
  admit_time[visit_key] = time

  # Create a unique key for each ICD code per visit
  code_key = sid SUBSEP hadm SUBSEP code

  # Only count each ICD code once per visit
  if (!(code_key in seen_code)) {
    seen_code[code_key] = 1
    code_count[visit_key]++
  }
}

END {
  print "subject_id","hadm_id","admittime","icd_code_count"

  for (k in admit_time) {
    split(k, parts, SUBSEP)
    sid  = parts[1]
    hadm = parts[2]

    print sid, hadm, admit_time[k], code_count[k] + 0
  }
}
' "${OUT}/filtered_sample.tsv" \
| sort -t$'\t' -k1,1n -k3,3 \
> "${OUT}/patient_visits.tsv"

echo "Created: ${OUT}/patient_visits.tsv"
wc -l "${OUT}/patient_visits.tsv"
head -n 5 "${OUT}/patient_visits.tsv"


# =========================================================
# PART 4B: Anchoring Years
#
# Goal:
# Extract earliest year from anchor_year_group
#
# Example:
#   "2008 - 2016" → "2008"
#
# Important functions:
#   - sub() removes text after "-"
#   - gsub() removes spaces
# =========================================================

echo "=== PART 4B: Anchoring Years ==="

awk -F',' '
BEGIN { OFS="\t" }

NR == 1 { next }

{
  sid = $1
  year_group = $5

  # Keep only the first year
  sub(/ - .*/, "", year_group)

  # Remove spaces
  gsub(/[[:space:]]/, "", year_group)

  print sid, year_group
}
' "${DATA}/bc_patients.csv" \
| sort -t$'\t' -k1,1n \
> "${OUT}/anchoring_years.tsv"

echo "Created: ${OUT}/anchoring_years.tsv"
wc -l "${OUT}/anchoring_years.tsv"
head -n 5 "${OUT}/anchoring_years.tsv"

echo "=== (Part 2 + Part 4) complete ==="
awk -F'\t' 'NR==1 { next }

# First pass: compute cohort-level stats from pre_dx_visits
{
  pv = $3

  vals[n] = pv

  if (n == 0 || pv < min) min = pv
  if (n == 0 || pv > max) max = pv

  sum += pv
  sumsq += pv * pv
  n++
}

END {
  mean = sum / n
  std = sqrt((sumsq / n) - (mean * mean))

  # sort values for quartiles
  for (i = 1; i < n; i++) {
    key = vals[i]
    j = i - 1
    while (j >= 0 && vals[j] > key) {
      vals[j+1] = vals[j]
      j--
    }
    vals[j+1] = key
  }

  q1 = vals[int((n + 3) / 4)]
  median = vals[int((n + 1) / 2)]
  q3 = vals[int((3 * n + 1) / 4)]

  # save stats for second pass
  printf "%.6f\t%.6f\t%d\t%d\t%d\t%d\t%d\n", mean, std, min, max, q1, median, q3 > "out/stats.tmp"
}
' out/buckets.tsv

awk -F'\t' '
BEGIN {
  OFS="\t"

  # read saved cohort-level stats
  getline line < "out/stats.tmp"
  split(line, s, "\t")

  mean = s[1]
  std = s[2]
  min = s[3]
  max = s[4]
  q1 = s[5]
  median = s[6]
  q3 = s[7]

  # print header
  printf "subject_id\ttotal_visits\tpre_dx_visits\tzscore\toutlier\n"
}

NR==1 { next }

{
  sid = $1
  tv = $2
  pv = $3

  # compute z-score
  if (std == 0) {
    z = 0
  } else {
    z = (pv - mean) / std
  }

  # classify outliers
  if (z >= 3 || z <= -3) {
    out = "EXTREME"
  } else if (z >= 2 || z <= -2) {
    out = "MODERATE"
  } else {
    out = "NO"
  }

  # print one row per patient
  printf "%s\t%d\t%d\t%.3f\t%s\n", sid, tv, pv, z, out
}

END {
  # print cohort-level summary stats at the bottom
  printf "# mean=%.3f std=%.3f min=%d max=%d\n", mean, std, min, max
  printf "# q1=%d median=%d q3=%d\n", q1, median, q3
}
' out/buckets.tsv > out/patient_summary.tsv

rm -f out/stats.tmp

echo "patient summary written"
head -n 5 out/patient_summary.tsv
tail -n 3 out/patient_summary.tsv
